from typing import Literal

from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field

from app.api_utils import json_error, start_tool_task
from app.auth import require_current_user
from app.task_runners import run_report_compile_task

router = APIRouter(prefix="/api/reports", tags=["reports"])

ReportTemplateType = Literal[
    "device_survey",
    "detection_plan",
    "detection_record",
    "detection_report",
    "data_retention",
    "item_confirmation",
    "device_basic_info",
    "basic_test_record",
    "issue_statistics",
]


class ReportCompileRequest(BaseModel):
    template_type: ReportTemplateType = "device_survey"
    project_name: str = ""
    report_title: str = ""
    report_no: str = ""
    sample_name: str = ""
    sample_model: str = ""
    sample_serial: str = ""
    device_name: str = ""
    device_type: str = ""
    device_no: str = ""
    device_level: str = ""
    department: str = ""
    manufacturer: str = ""
    target_ip: str = ""
    operating_system: str = ""
    open_ports: str = ""
    interface_type: str = ""
    protocol: str = ""
    software_version: str = ""
    network_status: str = ""
    device_status: str = ""
    support_software: str = ""
    source_code_available: str = ""
    upper_machine: str = ""
    lower_machine: str = ""
    other_devices: str = ""
    commissioning_org: str = ""
    commissioning_org_address: str = ""
    contact_name: str = ""
    contact_phone: str = ""
    contact_email: str = ""
    test_location: str = ""
    receive_date: str = ""
    test_date: str = ""
    report_date: str = ""
    environment_temperature: str = ""
    environment_humidity: str = ""
    basis_document: str = ""
    detection_conclusion: str = ""
    risk_summary: str = ""
    recommendations: str = ""
    testers: str = ""
    reviewer: str = ""
    approver: str = ""
    document_identifier: str = ""
    classification: str = ""
    issuing_unit: str = ""
    inspected_unit: str = ""
    testing_unit: str = ""
    signature_date: str = ""
    detection_date_start: str = ""
    detection_date_end: str = ""
    test_purpose: str = ""
    basis_documents_table: str = ""
    basis_attachments: str = ""
    sample_list_table: str = ""
    test_environment: str = ""
    test_tools_table: str = ""
    tool_calibration_attachments: str = ""
    result_summary_table: str = ""
    overall_risk_assessment: str = ""
    disposal_recommendations: str = ""
    notes: str = ""
    selected_items: list[str] = Field(default_factory=list)
    retained_items: list[str] = Field(default_factory=list)
    retained_reason: str = ""
    data_retention_sections_json: str = ""
    data_retention_testing_agency: str = ""
    data_retention_tested_agency: str = ""
    data_retention_date: str = ""
    non_test_reason: str = ""
    record_summary: str = ""
    problem_1: str = ""
    problem_2: str = ""
    problem_3: str = ""
    issue_description: str = ""
    issue_test_item: str = ""
    issue_fixable: str = ""
    issue_fix_action: str = ""
    issue_fix_plan: str = ""
    issue_unfixable_reason: str = ""
    issue_research_plan: str = ""
    issue_replacement_status: str = ""
    device_overview_intro: str = ""
    device_overview_usage: str = ""
    device_overview_classification: str = ""
    device_overview_procurement_time: str = ""
    device_overview_procurement_channel: str = ""
    hardware_composition_text: str = ""
    hardware_connection_text: str = ""
    untested_parts_description: str = ""
    hardware_topology_file: str = ""
    software_composition_text: str = ""
    software_topology_file: str = ""
    basic_info_table_file: str = ""
    network_topology_text: str = ""
    network_classification: str = ""
    data_classification: str = ""
    network_topology_file: str = ""
    usage_in_service_status: str = ""
    usage_working_status: str = ""
    usage_abnormal_records: str = ""
    usage_recent_checks: str = ""
    related_documents_text: str = ""
    related_documents_file: str = ""
    detection_environment_location: str = ""
    detection_environment_devices: str = ""
    testing_tool_access_method: str = ""
    electromagnetic_environment: str = ""
    personnel_arrangement_text: str = ""
    detection_items_text: str = ""
    physical_protection: str = ""
    technical_protection: str = ""
    security_incident_description: str = ""
    task_background_text: str = ""
    related_units_info_table: str = ""
    task_entrust_files: str = ""
    management_files_table: str = ""
    top_level_files_table: str = ""
    measured_files_table: str = ""
    technical_documents_files: str = ""
    other_files_table: str = ""
    interface_docs_files: str = ""
    detection_goal_text: str = ""
    terms_abbreviations_table: str = ""
    detection_period_start: str = ""
    detection_period_end: str = ""
    detection_place_text: str = ""
    schedule_table: str = ""
    project_plan_file: str = ""
    object_device_intro: str = ""
    object_hardware_desc: str = ""
    object_hardware_diagram_file: str = ""
    object_software_desc: str = ""
    object_software_diagram_file: str = ""
    object_basic_info_table: str = ""
    object_initial_state: str = ""
    object_document_list: str = ""
    object_document_files: str = ""
    content_selection_table: str = ""
    unselected_reason_table: str = ""
    exemption_files: str = ""
    environment_requirements_text: str = ""
    environment_confirmation_file: str = ""
    compliance_check_methods: str = ""
    compliance_check_files: str = ""
    wired_methods: str = ""
    wired_files: str = ""
    wireless_methods: str = ""
    wireless_files: str = ""
    firmware_methods: str = ""
    firmware_files: str = ""
    vulnerability_methods: str = ""
    vulnerability_files: str = ""
    electromagnetic_device_methods: str = ""
    electromagnetic_device_files: str = ""
    electromagnetic_peripheral_methods: str = ""
    electromagnetic_peripheral_files: str = ""
    nondestructive_methods: str = ""
    nondestructive_files: str = ""
    data_acceptance_text: str = ""
    data_acceptance_file: str = ""
    pause_resume_termination_text: str = ""
    institution_personnel_table: str = ""
    measured_unit_personnel_table: str = ""
    condition_support_text: str = ""
    condition_support_file: str = ""
    product_review_plan_table: str = ""
    config_review_plan_table: str = ""
    risk_management_table: str = ""
    safe_production_text: str = ""
    safe_production_file: str = ""
    confidentiality_text: str = ""
    confidentiality_files: str = ""
    other_matters_text: str = ""
    other_matters_files: str = ""
    selected_items_text: str = ""
    item_confirmation_sections_json: str = ""
    item_confirmation_selected_text: str = ""
    item_confirmation_unselected_text: str = ""
    compliance_check: str = ""
    compliance_reason_select: str = ""
    compliance_reason_other: str = ""
    wired_check: str = ""
    wired_reason_select: str = ""
    wired_reason_other: str = ""
    wireless_check: str = ""
    wireless_reason_select: str = ""
    wireless_reason_other: str = ""
    firmware_check: str = ""
    firmware_reason_select: str = ""
    firmware_reason_other: str = ""
    vulnerability_check: str = ""
    vulnerability_reason_select: str = ""
    vulnerability_reason_other: str = ""
    electromagnetic_device_check: str = ""
    electromagnetic_device_reason_select: str = ""
    electromagnetic_device_reason_other: str = ""
    electromagnetic_peripheral_check: str = ""
    electromagnetic_peripheral_reason_select: str = ""
    electromagnetic_peripheral_reason_other: str = ""
    nondestructive_check: str = ""
    nondestructive_reason_select: str = ""
    nondestructive_reason_other: str = ""
    record_common_rule: str = ""
    record_attachment_rule: str = ""
    record_compliance_1_process: str = ""
    record_compliance_1_result: str = ""
    record_compliance_1_result_note: str = ""
    record_compliance_1_files: str = ""
    record_compliance_2_process: str = ""
    record_compliance_2_result: str = ""
    record_compliance_2_result_note: str = ""
    record_compliance_2_files: str = ""
    record_compliance_3_process: str = ""
    record_compliance_3_result: str = ""
    record_compliance_3_result_note: str = ""
    record_compliance_3_files: str = ""
    record_wired_1_process: str = ""
    record_wired_1_result: str = ""
    record_wired_1_result_note: str = ""
    record_wired_1_files: str = ""
    record_wired_2_process: str = ""
    record_wired_2_result: str = ""
    record_wired_2_result_note: str = ""
    record_wired_2_files: str = ""
    record_wireless_1_process: str = ""
    record_wireless_1_result: str = ""
    record_wireless_1_result_note: str = ""
    record_wireless_1_files: str = ""
    record_wireless_2_process: str = ""
    record_wireless_2_result: str = ""
    record_wireless_2_result_note: str = ""
    record_wireless_2_files: str = ""
    record_wireless_3_process: str = ""
    record_wireless_3_result: str = ""
    record_wireless_3_result_note: str = ""
    record_wireless_3_files: str = ""
    record_firmware_1_process: str = ""
    record_firmware_1_result: str = ""
    record_firmware_1_result_note: str = ""
    record_firmware_1_files: str = ""
    record_firmware_2_process: str = ""
    record_firmware_2_result: str = ""
    record_firmware_2_result_note: str = ""
    record_firmware_2_files: str = ""
    record_firmware_3_process: str = ""
    record_firmware_3_result: str = ""
    record_firmware_3_result_note: str = ""
    record_firmware_3_files: str = ""
    record_firmware_4_process: str = ""
    record_firmware_4_result: str = ""
    record_firmware_4_result_note: str = ""
    record_firmware_4_files: str = ""
    record_firmware_5_process: str = ""
    record_firmware_5_result: str = ""
    record_firmware_5_result_note: str = ""
    record_firmware_5_files: str = ""
    record_firmware_6_process: str = ""
    record_firmware_6_result: str = ""
    record_firmware_6_result_note: str = ""
    record_firmware_6_files: str = ""
    record_firmware_7_process: str = ""
    record_firmware_7_result: str = ""
    record_firmware_7_result_note: str = ""
    record_firmware_7_files: str = ""
    record_firmware_8_process: str = ""
    record_firmware_8_result: str = ""
    record_firmware_8_result_note: str = ""
    record_firmware_8_files: str = ""
    record_firmware_9_process: str = ""
    record_firmware_9_result: str = ""
    record_firmware_9_result_note: str = ""
    record_firmware_9_files: str = ""
    record_vulnerability_1_process: str = ""
    record_vulnerability_1_result: str = ""
    record_vulnerability_1_result_note: str = ""
    record_vulnerability_1_files: str = ""
    record_vulnerability_2_process: str = ""
    record_vulnerability_2_result: str = ""
    record_vulnerability_2_result_note: str = ""
    record_vulnerability_2_files: str = ""
    record_vulnerability_3_process: str = ""
    record_vulnerability_3_result: str = ""
    record_vulnerability_3_result_note: str = ""
    record_vulnerability_3_files: str = ""
    record_vulnerability_4_process: str = ""
    record_vulnerability_4_result: str = ""
    record_vulnerability_4_result_note: str = ""
    record_vulnerability_4_files: str = ""
    record_electromagnetic_device_1_process: str = ""
    record_electromagnetic_device_1_result: str = ""
    record_electromagnetic_device_1_result_note: str = ""
    record_electromagnetic_device_1_files: str = ""
    record_electromagnetic_device_2_process: str = ""
    record_electromagnetic_device_2_result: str = ""
    record_electromagnetic_device_2_result_note: str = ""
    record_electromagnetic_device_2_files: str = ""
    record_electromagnetic_peripheral_1_process: str = ""
    record_electromagnetic_peripheral_1_result: str = ""
    record_electromagnetic_peripheral_1_result_note: str = ""
    record_electromagnetic_peripheral_1_files: str = ""
    record_electromagnetic_peripheral_2_process: str = ""
    record_electromagnetic_peripheral_2_result: str = ""
    record_electromagnetic_peripheral_2_result_note: str = ""
    record_electromagnetic_peripheral_2_files: str = ""
    record_nondestructive_1_process: str = ""
    record_nondestructive_1_result: str = ""
    record_nondestructive_1_result_note: str = ""
    record_nondestructive_1_files: str = ""
    record_nondestructive_2_process: str = ""
    record_nondestructive_2_result: str = ""
    record_nondestructive_2_result_note: str = ""
    record_nondestructive_2_files: str = ""
    record_nondestructive_3_process: str = ""
    record_nondestructive_3_result: str = ""
    record_nondestructive_3_result_note: str = ""
    record_nondestructive_3_files: str = ""


@router.post("/compile")
def compile_report(req: ReportCompileRequest, current_user=Depends(require_current_user)):
    if not current_user:
        return json_error("未登录或登录已过期，请重新登录。", 401)

    payload = req.model_dump()
    template_type = payload.get("template_type") or "device_survey"
    report_no = (payload.get("report_no") or "").strip()
    project_name = (payload.get("project_name") or "").strip()
    sample_name = (payload.get("sample_name") or "").strip()
    device_name = (payload.get("device_name") or "").strip()
    if not report_no and not project_name and not sample_name and not device_name:
        return {"code": 400, "message": "请至少填写报告编号、项目名称、样品名称或设备名称中的一项。", "data": ""}

    target = report_no or project_name or sample_name or device_name or template_type
    return start_tool_task(
        "report_compile",
        target,
        run_report_compile_task,
        payload,
        extra_data={
            "template_type": template_type,
            "report_no": report_no,
            "project_name": project_name,
            "sample_name": sample_name,
            "device_name": device_name,
        },
        operator=current_user["username"],
        task_name=report_title or report_no or project_name or sample_name or "报告编制任务",
        operation_type="生成报告包",
        source_module=f"report_{template_type}",
    )
